version: '2'
services:
  frontend-service:
    build: ./frontend-service
    environment:
    - LOGGER="${LOGGER}"
    ports:
      - "28181:8080"
    links:
      - "account-service"
      - "catalog-service"
      - "order-service"
  account-service:
    build: ./account-service
    environment:
    - LOGGER="${LOGGER}"
  catalog-service:
    build: ./catalog-service
    environment:
    - LOGGER="${LOGGER}"
  order-service:
    build: ./order-service
    environment:
    - LOGGER="${LOGGER}"

