---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      type: order-service
      app: jpetstore
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: order-service
        app: jpetstore
    spec:
      containers:
      - name: order-service
        image: 10.81.208.53:5000/jpetstore-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: configmap-order-service
        readinessProbe:
          httpGet:
            path: /jpetstore-order/
            port: 8180
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /jpetstore-order/
            port: 8180
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-order-service
data:
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_CONFIG_TEMPLATE_ID: "order-service"
  LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_MANAGER_KEY: "p5IsZQME5ORlIf2hbi0ooyXzpHD7Tz6gjc9yYySyU7VxsBD508y0O%2BBa6jiC4aiHLdr%2BXhCYzSNNxWkkKNM1ow%3D%3D"
  LENA_LICENSE_DOWNLOAD_URL: "manager"
  LENA_CONTRACT_CODE: "pghzJJqTdzaGtTuASr8yfw=="
  JAVA_DOMAIN_CACHE_TTL: "3"
  JPETSTORE_DOMAIN: ".default.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    type: order-service
    app: jpetstore
  ports:
  - port: 8180
    targetPort: 8180