---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  selector:
    matchLabels:
      type: catalog-service
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: lenasupport/jpetstore-catalog-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: configmap-catalog-service
        readinessProbe:
          httpGet:
            path: /
            port: 8180
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 8180
          initialDelaySeconds: 10
          periodSeconds: 60
      volumes:
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-catalog-service
data:
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_CONFIG_TEMPLATE_ID: "catalog-service"
  LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_MANAGER_KEY: "p5IsZQME5ORlIf2hbi0ooyXzpHD7Tz6gjc9yYySyU7VxsBD508y0O%2BBa6jiC4aiHLdr%2BXhCYzSNNxWkkKNM1ow%3D%3D"
  LENA_LICENSE_DOWNLOAD_URL: "manager"
  LENA_CONTRACT_CODE: "pghzJJqTdzaGtTuASr8yfw=="
  JAVA_DOMAIN_CACHE_TTL: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    type: catalog-service
  ports:
  - port: 8180
    targetPort: 8180